# This is a basic workflow to help you get started with Actions

name: Buidl and deploy Jekyll site to Github pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "github-pages"
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
  #  steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   #   - uses: actions/checkout@v2

      # Runs a single command using the runners shell
    #  - name: Run a one-line script
     #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
       # run: |
        #  echo Add other actions to build,
         # echo test, and deploy your project.
